index:
    path: /
    # controller: App\Controller\DefaultController::index
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
        path: '/%locale%'
        permanent: true
